In [16]:
file1 = open('f.txt', 'r') 
count = 0
  
while True: 
    count += 1
  
    # Get next line from file 
    line = file1.readline() 
  
    # if line is empty 
    # end of file is reached 
    if not line: 
        break
    print("Line{}: {}".format(count, line.strip())) 
    if count == 2:
        break
file1.close() 

Line1: 68037543430
Line2: -21123414637


In [38]:
arr = []
with open("f.txt", 'r') as f:
    lines = f.readlines()


In [39]:
new_arr = [int(item.strip()) for item in lines]

In [40]:
import numpy as np

In [41]:
np_arr = np.array(new_arr)

In [42]:
np_arr.sort()

In [64]:
test_max = np_arr[np_arr[0] + 10000 > np_arr]

In [53]:
test_max[np_arr[0] + 10000 < test_max]

array([], dtype=int64)

In [57]:
np_arr[0]

-99999887310

In [58]:
-99999887310 - 10000


-99999897310

In [65]:
len(test_max)

1

In [66]:
test_max

array([-99999887310])

In [ ]:
result_arr = np.array([])
for idx, item in enumerate(np_arr):
    sum_arr = np_arr + item
    sum_arr = sum_arr[sum_arr >= -10000]
    sum_arr = sum_arr[sum_arr <= 10000]
    result_arr = np.append(result_arr, np.unique(sum_arr))
    result_arr = np.unique(result_arr)
    
    if idx % 1000==0:
        print(idx)
        print(len(result_arr))

0
0
1000
78
2000
144
3000
189
4000
232
5000
261
6000
273
7000
290
8000
299
9000
312
10000
318
11000
324
12000
332
13000
339
14000
346
15000
352
16000
353
17000
357
18000
361
19000
365
20000
369
21000
370
22000
373
23000
377
24000
380
25000
381
26000
385
27000
385
28000
387
29000
389
30000
392
31000
393
32000
394
33000
394
34000
394
35000
395
36000
397
37000
398
38000
400
39000
402
40000
402
41000
403
42000
403
43000
405
44000
405
45000
406
46000
407
47000
408
48000
408
49000
408
50000
409
51000
409
52000
409
53000
409
54000
410
55000
410
56000
410
57000
410
58000
411
59000
412
60000
412
61000
412
62000
412
63000
412
64000
412
65000
412
66000
412
67000
412
68000
413
69000
413
70000
413
71000
413
72000
413
73000
413
74000
413
75000
414
76000
414
77000
414
78000
414
79000
414
80000
414
81000
415
82000
415
83000
415
84000
415
85000
415
86000
415
87000
415
88000
415
89000
415
90000
415
91000
415
92000
416
93000
416
94000
416
95000
416
96000
417
97000
417
98000
417
99000
417
100000
417
10100

756000
427
757000
427
758000
427
759000
427
760000
427
761000
427
762000
427
763000
427
764000
427
765000
427
766000
427
767000
427
768000
427
769000
427
770000
427
771000
427
772000
427
773000
427
774000
427
775000
427
776000
427
777000
427
778000
427
779000
427
780000
427
781000
427
782000
427
783000
427
784000
427
785000
427
786000
427
787000
427
788000
427
789000
427
790000
427
791000
427
792000
427
793000
427
794000
427
795000
427
796000
427
797000
427
798000
427
799000
427
800000
427
801000
427
802000
427
803000
427
804000
427
805000
427
806000
427
807000
427
808000
427
809000
427
810000
427
811000
427
812000
427
813000
427
814000
427
815000
427
816000
427
817000
427
818000
427
819000
427
820000
427
821000
427
822000
427
823000
427
824000
427
825000
427
826000
427
827000
427
828000
427
829000
427
830000
427
831000
427
832000
427
833000
427
834000
427
835000
427
836000
427
837000
427
838000
427
839000
427
840000
427
841000
427
842000
427
843000
427
844000
427
845000
427
846000
427

In [106]:
result_arr

array([8940.])

In [107]:
sum_arr

array([8940])

In [95]:
len(np.unique(sum_arr))

999752

In [113]:
hash = {}
count = 0
input_file = open('f.txt')
for line in input_file:
        num = int(line.rstrip('\n'))
        hash[num] = 1
input_file.close()

def target_sum (t):
        for element in hash:
                t_el = t-element
                if t_el in hash and t_el != element:
                        return 1
        return 0

for i in range(-10000,10000):
    if i % 100 == 0:
        print(i)
    if target_sum(i):
        count += 1
print(count)

-10000
-9900
-9800
-9700
-9600
-9500


KeyboardInterrupt: 